name: Build & Deploy Infra

on:
  push:
    branches: ["main"]
  workflow_dispatch:   

jobs:
  deploy:
    permissions:
      id-token: write  
      contents: read

    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-central1
      IMAGE_URI: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/myregistry/simpletimeservice:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Configure gcloud
      run: gcloud config set project $PROJECT_ID

    - name: Enable Artifact Registry Docker auth
      run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Build Docker image
      working-directory: ./app
      run: |
        docker build -t $IMAGE_URI .

    - name: Push image
      run: docker push $IMAGE_URI

    # - name: Install Terraform
    #   uses: hashicorp/setup-terraform@v3

    # - name: Terraform Init
    #   working-directory: ./terraform
    #   run: terraform init -input=false

    # - name: Terraform Plan
    #   working-directory: ./terraform
    #   run: terraform plan -out=tfplan

    # - name: Terraform Apply
    #   working-directory: ./terraform
    #   run: terraform apply -auto-approve tfplan
